# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorkflowyCli < Formula
  desc "CLI for Workflowy with crud operations and usage reports"
  homepage "https://github.com/mholzen/workflowy"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mholzen/workflowy/releases/download/v0.7.2/workflowy_0.7.2_Darwin_x86_64.tar.gz"
      sha256 "b6c71f4cbd90b4539769d5a9451cb10ebb49aff8b29d84ef642d4c85868257eb"

      def install
        bin.install "workflowy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mholzen/workflowy/releases/download/v0.7.2/workflowy_0.7.2_Darwin_arm64.tar.gz"
      sha256 "d8daa138d1cefc1a6296b1a55eb2c93414794ff36e7044383b3defa2284cb9ea"

      def install
        bin.install "workflowy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholzen/workflowy/releases/download/v0.7.2/workflowy_0.7.2_Linux_x86_64.tar.gz"
      sha256 "18255477bcab05b7504add9e6a01ac864cbaa6b3ac9ff96b27edf57296915191"
      def install
        bin.install "workflowy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholzen/workflowy/releases/download/v0.7.2/workflowy_0.7.2_Linux_arm64.tar.gz"
      sha256 "7e56df46deaafa6f6b8652f9d2413d63429d84028b9cf2bfd939b9d4dea5e516"
      def install
        bin.install "workflowy"
      end
    end
  end

  test do
    system "#{bin}/workflowy version"
  end
end
