# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workflowy < Formula
  desc "CLI for Workflowy with analytics and reporting"
  homepage "https://github.com/mholzen/workflowy"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mholzen/workflowy/releases/download/v0.2.0/workflowy_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "1afc9f310e84d8e8e41a9f053d796f83aefa12c584f9c936271cb15e2244b923"

      def install
        bin.install "workflowy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mholzen/workflowy/releases/download/v0.2.0/workflowy_0.2.0_Darwin_arm64.tar.gz"
      sha256 "d35d7869c09064166f5e8c7ff5f34a3314bb9f35bb8ca2f8d5d6db48d650a135"

      def install
        bin.install "workflowy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholzen/workflowy/releases/download/v0.2.0/workflowy_0.2.0_Linux_x86_64.tar.gz"
      sha256 "ba2c1a5ec7b6f661d3bb387aa69fd9606090016c119adffeeb558b223fbe514f"
      def install
        bin.install "workflowy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholzen/workflowy/releases/download/v0.2.0/workflowy_0.2.0_Linux_arm64.tar.gz"
      sha256 "cfe4d3513683694add4c8208991fad19ba9cc873441a141c9e3acd4c6ffbc0aa"
      def install
        bin.install "workflowy"
      end
    end
  end

  test do
    system "#{bin}/workflowy version"
  end
end
