# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorkflowyCli < Formula
  desc "CLI for Workflowy with crud operations and usage reports"
  homepage "https://github.com/mholzen/workflowy"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mholzen/workflowy/releases/download/v0.5.0/workflowy_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "fbfb7259a013eefa304170bf8a11a5eef5cca48943039a90514e5188ba174943"

      def install
        bin.install "workflowy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mholzen/workflowy/releases/download/v0.5.0/workflowy_0.5.0_Darwin_arm64.tar.gz"
      sha256 "15c71c910f3060d6c77d253aa3fe267469e22f07224f0a496f18536100f340fe"

      def install
        bin.install "workflowy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholzen/workflowy/releases/download/v0.5.0/workflowy_0.5.0_Linux_x86_64.tar.gz"
      sha256 "ae13141def686390e18d2182b628a1804681c5c53d9e63c7e62661341c6ada83"
      def install
        bin.install "workflowy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholzen/workflowy/releases/download/v0.5.0/workflowy_0.5.0_Linux_arm64.tar.gz"
      sha256 "dd0c6875e8b8a8e4b791c76de017cc14f9f62425777c554bfff2037662e095c5"
      def install
        bin.install "workflowy"
      end
    end
  end

  test do
    system "#{bin}/workflowy version"
  end
end
